import type { Order } from '@/types/order'
import type { Driver } from '@/types/driver'
import type { EarningsSummary } from '@/types/earnings'

export const MOCK_DRIVER: Driver = {
  id: 'driver-1',
  name: 'Luis',
  avatarInitials: 'LG',
  vehicle: { type: 'moto', brand: 'Italika', model: '250' },
  platforms: ['uber', 'rappi', 'didi'],
  rating: 4.97,
  totalDeliveries: 1842,
  memberSince: 'Marzo 2023',
}

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: '1842',
    platform: 'rappi',
    restaurantName: 'La Pasta Italiana',
    earnings: 71,
    pickup: {
      name: 'La Pasta Italiana',
      address: 'Av. Hidalgo 231',
      neighborhood: 'Centro',
      lat: 25.6866,
      lng: -100.3161,
    },
    dropoff: {
      address: 'Calle Morelos 540',
      neighborhood: 'Obispado',
      lat: 25.6794,
      lng: -100.3289,
    },
    distanceKm: 1.8,
    estimatedMinutes: 6,
    extraDistanceKm: 1.8,
    extraMinutes: 6,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 203,
    earningsPerKm: 39.44,
    recommendation: 'good',
    routeNumber: 1,
    status: 'heading_to_pickup',
    createdAt: new Date(Date.now() - 12 * 60000),
    acceptedAt: new Date(Date.now() - 10 * 60000),
  },
  {
    id: 'order-2',
    orderNumber: '8392',
    platform: 'uber',
    restaurantName: 'Restaurante XYZ',
    earnings: 94,
    pickup: {
      name: 'Restaurante XYZ',
      address: 'Av. Vasconcelos 400',
      neighborhood: 'San Pedro',
      lat: 25.6570,
      lng: -100.4017,
    },
    dropoff: {
      address: 'Av. Constitución 1830',
      neighborhood: 'Monterrey Centro',
      lat: 25.6726,
      lng: -100.3099,
    },
    distanceKm: 4.2,
    estimatedMinutes: 14,
    extraDistanceKm: 2.4,
    extraMinutes: 8,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 214,
    earningsPerKm: 22.38,
    recommendation: 'excellent',
    routeNumber: 2,
    status: 'accepted',
    createdAt: new Date(Date.now() - 3 * 60000),
    acceptedAt: new Date(Date.now() - 1 * 60000),
  },
  {
    id: 'order-3',
    orderNumber: '7741',
    platform: 'didi',
    restaurantName: 'Pizza Palace',
    earnings: 82,
    pickup: {
      name: 'Pizza Palace',
      address: 'Av. Garza Sada 2101',
      neighborhood: 'Tecnológico',
      lat: 25.6490,
      lng: -100.3167,
    },
    dropoff: {
      address: 'Blvd. Díaz Ordaz 320',
      neighborhood: 'Santa Catarina',
      lat: 25.6742,
      lng: -100.4619,
    },
    distanceKm: 6.1,
    estimatedMinutes: 19,
    extraDistanceKm: 3.9,
    extraMinutes: 13,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 198,
    earningsPerKm: 13.44,
    recommendation: 'neutral',
    routeNumber: 3,
    status: 'accepted',
    createdAt: new Date(Date.now() - 1 * 60000),
    acceptedAt: new Date(Date.now() - 30000),
  },
  {
    id: 'order-4',
    orderNumber: '2031',
    platform: 'rappi',
    restaurantName: 'Sushi Plus',
    earnings: 65,
    pickup: {
      name: 'Sushi Plus',
      address: 'Calle Hidalgo 450',
      neighborhood: 'Centro',
      lat: 25.6900,
      lng: -100.3120,
    },
    dropoff: {
      address: 'Av. Revolución 880',
      neighborhood: 'Monterrey',
      lat: 25.6820,
      lng: -100.3200,
    },
    distanceKm: 2.3,
    estimatedMinutes: 8,
    earningsPerKm: 28.26,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 45 * 60000),
    acceptedAt: new Date(Date.now() - 43 * 60000),
    deliveredAt: new Date(Date.now() - 35 * 60000),
  },
  {
    id: 'order-5',
    orderNumber: '9102',
    platform: 'uber',
    restaurantName: 'Tacos El Rey',
    earnings: 110,
    pickup: {
      name: 'Tacos El Rey',
      address: 'Av. Universidad 1200',
      neighborhood: 'Obispado',
      lat: 25.6750,
      lng: -100.3350,
    },
    dropoff: {
      address: 'Av. Lázaro Cárdenas 2400',
      neighborhood: 'San Nicolás',
      lat: 25.7230,
      lng: -100.3050,
    },
    distanceKm: 5.8,
    estimatedMinutes: 18,
    earningsPerKm: 18.97,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 90 * 60000),
    acceptedAt: new Date(Date.now() - 88 * 60000),
    deliveredAt: new Date(Date.now() - 72 * 60000),
  },
  {
    id: 'order-6',
    orderNumber: '6650',
    platform: 'didi',
    restaurantName: 'Burger Express',
    earnings: 88,
    pickup: {
      name: 'Burger Express',
      address: 'Av. Lázaro Cárdenas 1800',
      neighborhood: 'Guadalupe',
      lat: 25.6780,
      lng: -100.2580,
    },
    dropoff: {
      address: 'Calle Reforma 310',
      neighborhood: 'Monterrey Centro',
      lat: 25.6720,
      lng: -100.3080,
    },
    distanceKm: 4.9,
    estimatedMinutes: 16,
    earningsPerKm: 17.96,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 130 * 60000),
    deliveredAt: new Date(Date.now() - 115 * 60000),
  },
  {
    id: 'order-7',
    orderNumber: '3344',
    platform: 'rappi',
    restaurantName: 'Café Central',
    earnings: 55,
    pickup: {
      name: 'Café Central',
      address: 'Av. Vasconcelos 400',
      neighborhood: 'San Pedro',
      lat: 25.6568,
      lng: -100.4020,
    },
    dropoff: {
      address: 'Calle Monterrey 210',
      neighborhood: 'San Pedro',
      lat: 25.6620,
      lng: -100.3980,
    },
    distanceKm: 1.5,
    estimatedMinutes: 5,
    earningsPerKm: 36.67,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 180 * 60000),
    deliveredAt: new Date(Date.now() - 172 * 60000),
  },
  {
    id: 'order-8',
    orderNumber: '5521',
    platform: 'uber',
    restaurantName: 'La Parrilla Regia',
    earnings: 120,
    pickup: {
      name: 'La Parrilla Regia',
      address: 'Blvd. Díaz Ordaz 320',
      neighborhood: 'Santa Catarina',
      lat: 25.6740,
      lng: -100.4620,
    },
    dropoff: {
      address: 'Av. Morones Prieto 3000',
      neighborhood: 'Cumbres',
      lat: 25.7610,
      lng: -100.3960,
    },
    distanceKm: 7.2,
    estimatedMinutes: 23,
    earningsPerKm: 16.67,
    recommendation: 'excellent',
    status: 'delivered',
    createdAt: new Date(Date.now() - 240 * 60000),
    deliveredAt: new Date(Date.now() - 220 * 60000),
  },
]

export const NEW_ORDER_POOL: Omit<Order, 'id' | 'createdAt' | 'status'>[] = [
  {
    orderNumber: '4471',
    platform: 'uber',
    restaurantName: 'Restaurante XYZ',
    earnings: 94,
    pickup: {
      name: 'Restaurante XYZ',
      address: 'Av. Vasconcelos 400',
      neighborhood: 'San Pedro',
      lat: 25.6570,
      lng: -100.4017,
    },
    dropoff: {
      address: 'Av. Constitución 1830',
      neighborhood: 'Monterrey',
      lat: 25.6726,
      lng: -100.3099,
    },
    distanceKm: 4.2,
    estimatedMinutes: 14,
    extraDistanceKm: 2.4,
    extraMinutes: 8,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 214,
    earningsPerKm: 22.38,
    recommendation: 'excellent',
  },
  {
    orderNumber: '9981',
    platform: 'rappi',
    restaurantName: 'Sushi Monterrey',
    earnings: 78,
    pickup: {
      name: 'Sushi Monterrey',
      address: 'Av. Revolución 1200',
      neighborhood: 'Monterrey',
      lat: 25.6826,
      lng: -100.3165,
    },
    dropoff: {
      address: 'Calle Padre Mier 800',
      neighborhood: 'Centro',
      lat: 25.6709,
      lng: -100.3070,
    },
    distanceKm: 3.1,
    estimatedMinutes: 10,
    extraDistanceKm: 1.6,
    extraMinutes: 5,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 208,
    earningsPerKm: 25.16,
    recommendation: 'good',
  },
  {
    orderNumber: '3312',
    platform: 'didi',
    restaurantName: 'Tacos de Canasta',
    earnings: 45,
    pickup: {
      name: 'Tacos de Canasta',
      address: 'Calle Juárez 450',
      neighborhood: 'Centro',
      lat: 25.6687,
      lng: -100.3097,
    },
    dropoff: {
      address: 'Av. Ruiz Cortines 3100',
      neighborhood: 'Linda Vista',
      lat: 25.7120,
      lng: -100.2980,
    },
    distanceKm: 5.4,
    estimatedMinutes: 17,
    extraDistanceKm: 3.8,
    extraMinutes: 12,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 184,
    earningsPerKm: 8.33,
    recommendation: 'bad',
  },
  {
    orderNumber: '7823',
    platform: 'uber',
    restaurantName: 'El Asador Regio',
    earnings: 115,
    pickup: {
      name: 'El Asador Regio',
      address: 'Av. Eugenio Garza Sada 3000',
      neighborhood: 'Tecnológico',
      lat: 25.6440,
      lng: -100.3200,
    },
    dropoff: {
      address: 'Av. Insurgentes 1540',
      neighborhood: 'Del Valle',
      lat: 25.6580,
      lng: -100.3440,
    },
    distanceKm: 3.8,
    estimatedMinutes: 12,
    extraDistanceKm: 1.9,
    extraMinutes: 6,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 228,
    earningsPerKm: 30.26,
    recommendation: 'excellent',
  },
]

export const MOCK_EARNINGS_SUMMARY: EarningsSummary = {
  total: 1284,
  perHour: 218,
  perKm: 18.4,
  totalOrders: 14,
  changePercent: 12.4,
  activeMinutes: 352,
  totalKm: 69.8,
  hourly: [
    { hour: 8, label: '8AM', earnings: 142, orders: 2 },
    { hour: 9, label: '9AM', earnings: 188, orders: 2 },
    { hour: 10, label: '10AM', earnings: 96, orders: 1 },
    { hour: 11, label: '11AM', earnings: 0, orders: 0 },
    { hour: 12, label: '12PM', earnings: 210, orders: 3 },
    { hour: 13, label: '1PM', earnings: 178, orders: 2 },
    { hour: 14, label: '2PM', earnings: 124, orders: 1 },
    { hour: 15, label: '3PM', earnings: 0, orders: 0 },
    { hour: 16, label: '4PM', earnings: 88, orders: 1 },
    { hour: 17, label: '5PM', earnings: 258, orders: 3 },
  ],
  byPlatform: [
    { platform: 'uber', totalEarnings: 584, totalOrders: 6, earningsPerKm: 22.1, avgPerOrder: 97.3 },
    { platform: 'rappi', totalEarnings: 412, totalOrders: 5, earningsPerKm: 18.6, avgPerOrder: 82.4 },
    { platform: 'didi', totalEarnings: 288, totalOrders: 3, earningsPerKm: 15.2, avgPerOrder: 96.0 },
  ],
  bestHourRange: '7:00 PM – 10:00 PM',
  bestHourEarnings: 264,
  additionalEarningsFromVygo: 186,
  kmSaved: 24,
  minutesSaved: 47,
}
