import type { Order } from '@/types/order'
import type { Driver } from '@/types/driver'
import type { EarningsSummary } from '@/types/earnings'

export const MOCK_DRIVER: Driver = {
  id: 'driver-1',
  name: 'Luis',
  avatarInitials: 'LG',
  vehicle: { type: 'moto', brand: 'Italika', model: '250' },
  platforms: ['uber', 'rappi', 'didi'],
  rating: 4.97,
  totalDeliveries: 1842,
  memberSince: 'Marzo 2023',
}

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: '1842',
    platform: 'rappi',
    restaurantName: 'La Pasta Italiana',
    earnings: 71,
    pickup: {
      name: 'La Pasta Italiana',
      address: 'Av. Hidalgo 231',
      neighborhood: 'Centro',
      lat: 25.6866,
      lng: -100.3161,
    },
    dropoff: {
      address: 'Calle Morelos 540',
      neighborhood: 'Obispado',
      lat: 25.6794,
      lng: -100.3289,
    },
    distanceKm: 1.8,
    estimatedMinutes: 6,
    extraDistanceKm: 1.8,
    extraMinutes: 6,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 203,
    earningsPerKm: 39.44,
    recommendation: 'good',
    routeNumber: 1,
    status: 'heading_to_pickup',
    createdAt: new Date(Date.now() - 12 * 60000),
    acceptedAt: new Date(Date.now() - 10 * 60000),
  },
  {
    id: 'order-2',
    orderNumber: '8392',
    platform: 'uber',
    restaurantName: 'Restaurante XYZ',
    earnings: 94,
    pickup: {
      name: 'Restaurante XYZ',
      address: 'Av. Vasconcelos 400',
      neighborhood: 'San Pedro',
      lat: 25.6570,
      lng: -100.4017,
    },
    dropoff: {
      address: 'Av. Constitución 1830',
      neighborhood: 'Monterrey Centro',
      lat: 25.6726,
      lng: -100.3099,
    },
    distanceKm: 4.2,
    estimatedMinutes: 14,
    extraDistanceKm: 2.4,
    extraMinutes: 8,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 214,
    earningsPerKm: 22.38,
    recommendation: 'excellent',
    routeNumber: 2,
    status: 'accepted',
    createdAt: new Date(Date.now() - 3 * 60000),
    acceptedAt: new Date(Date.now() - 1 * 60000),
  },
  {
    id: 'order-3',
    orderNumber: '7741',
    platform: 'didi',
    restaurantName: 'Pizza Palace',
    earnings: 82,
    pickup: {
      name: 'Pizza Palace',
      address: 'Av. Garza Sada 2101',
      neighborhood: 'Tecnológico',
      lat: 25.6490,
      lng: -100.3167,
    },
    dropoff: {
      address: 'Blvd. Díaz Ordaz 320',
      neighborhood: 'Santa Catarina',
      lat: 25.6742,
      lng: -100.4619,
    },
    distanceKm: 6.1,
    estimatedMinutes: 19,
    extraDistanceKm: 3.9,
    extraMinutes: 13,
    currentEarningsPerHour: 192,
    projectedEarningsPerHour: 198,
    earningsPerKm: 13.44,
    recommendation: 'neutral',
    routeNumber: 3,
    status: 'accepted',
    createdAt: new Date(Date.now() - 1 * 60000),
    acceptedAt: new Date(Date.now() - 30000),
  },
  {
    id: 'order-4',
    orderNumber: '2031',
    platform: 'rappi',
    restaurantName: 'Sushi Plus',
    earnings: 65,
    pickup: {
      name: 'Sushi Plus',
      address: 'Calle Hidalgo 450',
      neighborhood: 'Centro',
      lat: 25.6900,
      lng: -100.3120,
    },
    dropoff: {
      address: 'Av. Revolución 880',
      neighborhood: 'Monterrey',
      lat: 25.6820,
      lng: -100.3200,
    },
    distanceKm: 2.3,
    estimatedMinutes: 8,
    earningsPerKm: 28.26,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 45 * 60000),
    acceptedAt: new Date(Date.now() - 43 * 60000),
    deliveredAt: new Date(Date.now() - 35 * 60000),
  },
  {
    id: 'order-5',
    orderNumber: '9102',
    platform: 'uber',
    restaurantName: 'Tacos El Rey',
    earnings: 110,
    pickup: {
      name: 'Tacos El Rey',
      address: 'Av. Universidad 1200',
      neighborhood: 'Obispado',
      lat: 25.6750,
      lng: -100.3350,
    },
    dropoff: {
      address: 'Av. Lázaro Cárdenas 2400',
      neighborhood: 'San Nicolás',
      lat: 25.7230,
      lng: -100.3050,
    },
    distanceKm: 5.8,
    estimatedMinutes: 18,
    earningsPerKm: 18.97,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 90 * 60000),
    acceptedAt: new Date(Date.now() - 88 * 60000),
    deliveredAt: new Date(Date.now() - 72 * 60000),
  },
  {
    id: 'order-6',
    orderNumber: '6650',
    platform: 'didi',
    restaurantName: 'Burger Express',
    earnings: 88,
    pickup: {
      name: 'Burger Express',
      address: 'Av. Lázaro Cárdenas 1800',
      neighborhood: 'Guadalupe',
      lat: 25.6780,
      lng: -100.2580,
    },
    dropoff: {
      address: 'Calle Reforma 310',
      neighborhood: 'Monterrey Centro',
      lat: 25.6720,
      lng: -100.3080,
    },
    distanceKm: 4.9,
    estimatedMinutes: 16,
    earningsPerKm: 17.96,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 130 * 60000),
    deliveredAt: new Date(Date.now() - 115 * 60000),
  },
  {
    id: 'order-7',
    orderNumber: '3344',
    platform: 'rappi',
    restaurantName: 'Café Central',
    earnings: 55,
    pickup: {
      name: 'Café Central',
      address: 'Av. Vasconcelos 400',
      neighborhood: 'San Pedro',
      lat: 25.6568,
      lng: -100.4020,
    },
    dropoff: {
      address: 'Calle Monterrey 210',
      neighborhood: 'San Pedro',
      lat: 25.6620,
      lng: -100.3980,
    },
    distanceKm: 1.5,
    estimatedMinutes: 5,
    earningsPerKm: 36.67,
    recommendation: 'good',
    status: 'delivered',
    createdAt: new Date(Date.now() - 180 * 60000),
    deliveredAt: new Date(Date.now() - 172 * 60000),
  },
  {
    id: 'order-8',
    orderNumber: '5521',
    platform: 'uber',
    restaurantName: 'La Parrilla Regia',
    earnings: 120,
    pickup: {
      name: 'La Parrilla Regia',
      address: 'Blvd. Díaz Ordaz 320',
      neighborhood: 'Santa Catarina',
      lat: 25.6740,
      lng: -100.4620,
    },
    dropoff: {
      address: 'Av. Morones Prieto 3000',
      neighborhood: 'Cumbres',
      lat: 25.7610,
      lng: -100.3960,
    },
    distanceKm: 7.2,
    estimatedMinutes: 23,
    earningsPerKm: 16.67,
    recommendation: 'excellent',
    status: 'delivered',
    createdAt: new Date(Date.now() - 240 * 60000),
    deliveredAt: new Date(Date.now() - 220 * 60000),
  },
]

// Pool alineado con COMERCIOS_MTY del backend.
// Precios: $54–$92 (rango del simulador). Dropoffs en zonas de alta demanda.
// El backend calcula ajuste_aprendido: centro +14, san_pedro +18, tec +12, periferia -16.
export const NEW_ORDER_POOL: Omit<Order, 'id' | 'createdAt' | 'status'>[] = [
  {
    // Sushi Roll Macroplaza → Centro (ajuste PPO: +14)
    orderNumber: '4471',
    platform: 'uber',
    restaurantName: 'Sushi Roll Macroplaza',
    earnings: 62,
    pickup: {
      name: 'Sushi Roll Macroplaza',
      address: 'Macroplaza, Centro',
      neighborhood: 'Centro',
      lat: 25.6698,
      lng: -100.3102,
    },
    dropoff: {
      address: 'Av. Constitución 1800',
      neighborhood: 'Centro',
      lat: 25.6720,
      lng: -100.3080,
    },
    distanceKm: 2.1,
    estimatedMinutes: 9,
    extraDistanceKm: 1.4,
    extraMinutes: 5,
    earningsPerKm: 29.5,
    recommendation: 'good',
  },
  {
    // Chilaquiles Tec → Tec (ajuste PPO: +12)
    orderNumber: '9981',
    platform: 'rappi',
    restaurantName: 'Chilaquiles Tec',
    earnings: 58,
    pickup: {
      name: 'Chilaquiles Tec',
      address: 'Av. Garza Sada 2101',
      neighborhood: 'Tecnológico',
      lat: 25.6515,
      lng: -100.2895,
    },
    dropoff: {
      address: 'Calle del Roble 300',
      neighborhood: 'Tecnológico',
      lat: 25.6540,
      lng: -100.2920,
    },
    distanceKm: 1.8,
    estimatedMinutes: 8,
    extraDistanceKm: 1.0,
    extraMinutes: 4,
    earningsPerKm: 32.2,
    recommendation: 'good',
  },
  {
    // Centrito Burgers → San Pedro (ajuste PPO: +18) — mejor zona
    orderNumber: '7823',
    platform: 'uber',
    restaurantName: 'Centrito Burgers',
    earnings: 66,
    pickup: {
      name: 'Centrito Burgers',
      address: 'Av. Vasconcelos 300',
      neighborhood: 'San Pedro',
      lat: 25.6580,
      lng: -100.3640,
    },
    dropoff: {
      address: 'Calz. del Valle 440',
      neighborhood: 'San Pedro',
      lat: 25.6610,
      lng: -100.3600,
    },
    distanceKm: 2.4,
    estimatedMinutes: 10,
    extraDistanceKm: 1.5,
    extraMinutes: 5,
    earningsPerKm: 27.5,
    recommendation: 'excellent',
  },
  {
    // Pangea Valle Oriente → San Pedro (ajuste PPO: +18)
    orderNumber: '3312',
    platform: 'didi',
    restaurantName: 'Pangea Express Valle Oriente',
    earnings: 74,
    pickup: {
      name: 'Pangea Express Valle Oriente',
      address: 'Av. David Alfaro Siqueiros 106',
      neighborhood: 'San Pedro',
      lat: 25.6420,
      lng: -100.3310,
    },
    dropoff: {
      address: 'Av. Insurgentes 1540',
      neighborhood: 'San Pedro',
      lat: 25.6580,
      lng: -100.3440,
    },
    distanceKm: 3.2,
    estimatedMinutes: 12,
    extraDistanceKm: 2.0,
    extraMinutes: 7,
    earningsPerKm: 23.1,
    recommendation: 'excellent',
  },
  {
    // La Lucha Sanguchería (Barrio Antiguo) → Centro — con surge
    orderNumber: '5519',
    platform: 'rappi',
    restaurantName: 'La Lucha Sanguchería',
    earnings: 87,  // surge ×1.4 aplicado
    pickup: {
      name: 'La Lucha Sanguchería Barrio Antiguo',
      address: 'Av. Dr. Coss 1024, Barrio Antiguo',
      neighborhood: 'Centro',
      lat: 25.6675,
      lng: -100.3060,
    },
    dropoff: {
      address: 'Av. Pino Suárez 800',
      neighborhood: 'Centro',
      lat: 25.6680,
      lng: -100.3100,
    },
    distanceKm: 1.4,
    estimatedMinutes: 7,
    extraDistanceKm: 0.8,
    extraMinutes: 3,
    earningsPerKm: 62.1,
    recommendation: 'excellent',
  },
  {
    // Tacos El Primo → Centro (ajuste PPO: +14) — precio base normal
    orderNumber: '6644',
    platform: 'didi',
    restaurantName: 'Tacos El Primo',
    earnings: 57,
    pickup: {
      name: 'Tacos El Primo',
      address: 'Av. Cuauhtémoc 400, Centro',
      neighborhood: 'Centro',
      lat: 25.6740,
      lng: -100.3160,
    },
    dropoff: {
      address: 'Av. Colón 720',
      neighborhood: 'Centro',
      lat: 25.6760,
      lng: -100.3120,
    },
    distanceKm: 1.9,
    estimatedMinutes: 9,
    extraDistanceKm: 1.1,
    extraMinutes: 4,
    earningsPerKm: 30.0,
    recommendation: 'good',
  },
  {
    // Sierra Madre Brewing → San Pedro (ajuste PPO: +18)
    orderNumber: '8831',
    platform: 'uber',
    restaurantName: 'Sierra Madre Brewing Co.',
    earnings: 71,
    pickup: {
      name: 'Sierra Madre Brewing Co.',
      address: 'Río Nazas 100, San Pedro',
      neighborhood: 'San Pedro',
      lat: 25.6520,
      lng: -100.3590,
    },
    dropoff: {
      address: 'Cumbres 3er Sector',
      neighborhood: 'San Pedro',
      lat: 25.6560,
      lng: -100.3550,
    },
    distanceKm: 2.7,
    estimatedMinutes: 11,
    extraDistanceKm: 1.6,
    extraMinutes: 6,
    earningsPerKm: 26.3,
    recommendation: 'good',
  },
  {
    // El Gran Pastor Gonzalitos → Centro (ajuste PPO: +14)
    orderNumber: '2277',
    platform: 'rappi',
    restaurantName: 'El Gran Pastor Gonzalitos',
    earnings: 61,
    pickup: {
      name: 'El Gran Pastor Gonzalitos',
      address: 'Blvd. Manuel Ávila Camacho 3000',
      neighborhood: 'Obispado',
      lat: 25.6880,
      lng: -100.3470,
    },
    dropoff: {
      address: 'Av. Hidalgo 2500',
      neighborhood: 'Centro',
      lat: 25.6720,
      lng: -100.3150,
    },
    distanceKm: 3.5,
    estimatedMinutes: 13,
    extraDistanceKm: 2.2,
    extraMinutes: 8,
    earningsPerKm: 17.4,
    recommendation: 'good',
  },
]

export const MOCK_EARNINGS_SUMMARY: EarningsSummary = {
  total: 1284,
  perHour: 218,
  perKm: 18.4,
  totalOrders: 14,
  changePercent: 12.4,
  activeMinutes: 352,
  totalKm: 69.8,
  hourly: [
    { hour: 8, label: '8AM', earnings: 142, orders: 2 },
    { hour: 9, label: '9AM', earnings: 188, orders: 2 },
    { hour: 10, label: '10AM', earnings: 96, orders: 1 },
    { hour: 11, label: '11AM', earnings: 0, orders: 0 },
    { hour: 12, label: '12PM', earnings: 210, orders: 3 },
    { hour: 13, label: '1PM', earnings: 178, orders: 2 },
    { hour: 14, label: '2PM', earnings: 124, orders: 1 },
    { hour: 15, label: '3PM', earnings: 0, orders: 0 },
    { hour: 16, label: '4PM', earnings: 88, orders: 1 },
    { hour: 17, label: '5PM', earnings: 258, orders: 3 },
  ],
  byPlatform: [
    { platform: 'uber', totalEarnings: 584, totalOrders: 6, earningsPerKm: 22.1, avgPerOrder: 97.3 },
    { platform: 'rappi', totalEarnings: 412, totalOrders: 5, earningsPerKm: 18.6, avgPerOrder: 82.4 },
    { platform: 'didi', totalEarnings: 288, totalOrders: 3, earningsPerKm: 15.2, avgPerOrder: 96.0 },
  ],
  bestHourRange: '7:00 PM – 10:00 PM',
  bestHourEarnings: 264,
  additionalEarningsFromVygo: 186,
  kmSaved: 24,
  minutesSaved: 47,
}
